# Generated by Django 2.2.4 on 2019-08-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190818_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
